// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUcTl_sC9ebnRn-o7nKixCK71xFJ5aNg',
    appId: '1:549872515513:web:6fc61781deff7908969e68',
    messagingSenderId: '549872515513',
    projectId: 'aqgm-d5c47',
    authDomain: 'aqgm-d5c47.firebaseapp.com',
    storageBucket: 'aqgm-d5c47.appspot.com',
    measurementId: 'G-VJXYEHXL6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0fyKoQoNUgO0qXHna6h4Sgx0efeMLyE',
    appId: '1:549872515513:android:1909157739ce5035969e68',
    messagingSenderId: '549872515513',
    projectId: 'aqgm-d5c47',
    storageBucket: 'aqgm-d5c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB454xJchOWkBnwU-lbzsCkA1HPjdeTTM8',
    appId: '1:549872515513:ios:73321c210ab1604a969e68',
    messagingSenderId: '549872515513',
    projectId: 'aqgm-d5c47',
    storageBucket: 'aqgm-d5c47.appspot.com',
    androidClientId: '549872515513-3hnslr3slqii0nerm8g6ll7ueqf5np06.apps.googleusercontent.com',
    iosClientId: '549872515513-bb1lep6vs4og6u75vngbu7b8u78ao2sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}